### ISSUE TITLE
Autocomplete problem

### ISSUE THREAD

**Issue by Mxater** [arvi/Agila-Theme#7]
Hello, I find a problem with the autocomplete suggestion.

When you use autocomplete, this not has diference into selected item and not selected items.

![2016-05-11 10_22_17-d__temp_sedi_cambio 5_ind_in_alumno php laramed cl multicaja sissalud anim](https://cloud.githubusercontent.com/assets/4630666/15182494/2eebfaa6-1763-11e6-8bc9-ee2e42e93580.png)

**Comment by arvi** [comment]
I agree, the highlighted text is not obvious. Will include this in my next update this week. :smile:

**Comment by agauniyal** [comment]
Was going to open another issue, glad you're already taking care of it :smile:. Also highlight color is a bit off the track too, makes reading the highlighted stuff hard. otherwise beautiful theme :+1:

**Comment by arvi** [comment]
@agauniyal Hello there 😄  What do you mean by highlighted stuff, do you mean the 'ReactDOM' part of the code on this below link:

`https://camo.githubusercontent.com/5406b3863b1da33d473eb3539468847aa30251c2/68747470733a2f2f7777772e64726f70626f782e636f6d2f732f6a743363686f7871366235383374372f4167696c612532305468656d652e706e673f7261773d31`

If yes, hmmm that would still be the default as I prefer subtle colors to not distract me with the rest of the code. What colors would you prefer so I can try to make options for it.

Thanks for the appreciation 😄

**Comment by arvi** [comment]
@agauniyal I think I finally get what you're saying. It's somehow unreadable when highlighted especially when a code block is highlighted and Sublime's window is active... Wow I didn't notice it :smile: Thanks for reporting. Will include that in my next push this weekend.

**Comment by agauniyal** [comment]
Example - `ctrl + a` selection highlight :smile:

**Comment by Mxater** [comment]
Not, not selection Highlight, is the Autocomplete suggestion menu, not show what is selected.

**Comment by Mxater** [comment]
This
![test](https://cloud.githubusercontent.com/assets/4630666/15433380/1eecb932-1e80-11e6-931d-8421655f1073.jpg)

Highlight the selecction in the autocomplete dropmenu

**Comment by arvi** [comment]
I'm currently working on both selection highlight and autocomplete right now. :smile:

**Comment by arvi** [comment]
Done. :smile: Thanks!

You can change to your liking with any of the ff (default: white):

```
"theme_agila_auto_complete_white": true,
"theme_agila_auto_complete_gray": true,
"theme_agila_auto_complete_lightblue": true,
"theme_agila_auto_complete_yellow": true,
"theme_agila_auto_complete_pink": true,
```

https://github.com/arvi/Agila-Theme/commit/10fc60b9d847cd794a9d38388b47ff009f29ae1e

**Comment by jtokoph** [comment]
@arvi I've updated to 1.5.0 but still don't see an active highlight on the currently selected auto-complete option in the dropdown.

What I see (one of the options should have a highlighted background):
![screen shot 2016-05-20 at 1 13 15 pm](https://cloud.githubusercontent.com/assets/346225/15440907/db7324fe-1e8c-11e6-9b10-5cfd781d2815.png)

It should look something like mxater posted above: https://github.com/arvi/Agila-Theme/issues/7#issuecomment-220642214

**Comment by jtokoph** [comment]
I think a similar layer0.tint is required on a selected table row:
https://github.com/ctf0/Seti_ST3/blob/fb4b1ee69e94ac9584123c636fa716dd1eb35fde/Seti.sublime-theme#L1132

**Comment by jtokoph** [comment]
It looks like this is properly set for the quick actions:
![screen shot 2016-05-20 at 1 28 24 pm](https://cloud.githubusercontent.com/assets/346225/15441259/c7e6b28c-1e8e-11e6-8217-a851ee5dcf37.png)

Although I would recommend setting the color to something lighter to give more contrast to the non selected rows.

**Comment by arvi** [comment]
Done. Thanks for reporting... I didn't notice it 😛 

https://github.com/arvi/Agila-Theme/blob/master/messages/1.6.0.txt

https://github.com/arvi/Agila-Theme/commit/465e2352a4f3c646510e25a6ce5047379283a491

**Comment by jtokoph** [comment]
Looks great! Thanks!
